
document.getElementById("botijo0").addEventListener("mouseover",function(){
    this.style.color="yellow";
    this.style.backgroundColor="lightblue";
})
document.getElementById("botijo0").addEventListener("mouseout",function(){
    this.style.color="black";
    this.style.backgroundColor="";
})
document.getElementById("botijo1").addEventListener("mouseover",function(){
    this.style.color="yellow";
    this.style.backgroundColor="lightblue";
})
document.getElementById("botijo1").addEventListener("mouseout",function(){
    this.style.color="black";
    this.style.backgroundColor="";
})
document.getElementById("botijo2").addEventListener("mouseover",function(){
    this.style.color="yellow";
    this.style.backgroundColor="lightblue";
})
document.getElementById("botijo2").addEventListener("mouseout",function(){
    this.style.color="black";
    this.style.backgroundColor="";
})
document.getElementById("botijo3").addEventListener("mouseover",function(){
    this.style.color="yellow";
    this.style.backgroundColor="lightblue";
})
document.getElementById("botijo3").addEventListener("mouseout",function(){
    this.style.color="black";
    this.style.backgroundColor="";
})
document.getElementById("botijo4").addEventListener("mouseover",function(){
    this.style.color="yellow";
    this.style.backgroundColor="lightblue";
})
document.getElementById("botijo4").addEventListener("mouseout",function(){
    this.style.color="black";
    this.style.backgroundColor="";
})
